//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates, edited by
//  Behdad Keynejad for Snapp, so you can apply clean architecture to your
//  iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ___VARIABLE_sceneName___Presenter: SNPPresenter {
    // MARK: - Properties
    weak var viewController: ___VARIABLE_sceneName___ViewControllerProtocol!
    
    // MARK: - Methods
}

extension ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___PresenterProtocol {
    func present(businessModel: ___VARIABLE_sceneName___.Something.BusinessModel) {
        // Translate businessModel to viewModel
        
        viewController.display(viewModel: ___VARIABLE_sceneName___.Something.ViewModel)
    }
}
