//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates, edited by
//  Behdad Keynejad for Snapp, so you can apply clean architecture to your
//  iOS and Mac projects, see http://clean-swift.com
//

import XCTest
import SNPUtilities
@testable import ___PROJECTNAMEASIDENTIFIER___

class ___VARIABLE_sceneName___InteractorTests: XCTestCase {
    // MARK: - Properties
    var testInteractor: ___VARIABLE_sceneName___Interactor!
    
    // MARK: - Methods
    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        setup___VARIABLE_sceneName___Interactor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    func setup___VARIABLE_sceneName___Interactor() {
        testInteractor = ___VARIABLE_sceneName___Interactor()
    }
    
    // MARK: Mocks
    class ___VARIABLE_sceneName___PresenterMock: ___VARIABLE_sceneName___PresenterProtocol {
    }
    
    // MARK: - Tests
    func testDoSomething() {
        // Given
        let mockPresenter = ___VARIABLE_sceneName___PresenterMock()
        testInteractor.presenter = mockPresenter
//        let request = ___VARIABLE_sceneName___.Something.Request()
        
        // When
//        testInteractor.doSomething(request: request)
        
        // Then
//        XCTAssertTrue(mockPresenter.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
