//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates, edited by
//  Behdad Keynejad for Snapp, so you can apply clean architecture to your
//  iOS and Mac projects, see http://clean-swift.com
//

import XCTest
@testable import ___PROJECTNAMEASIDENTIFIER___

class ___VARIABLE_sceneName___ViewControllerTests: XCTestCase {
    // MARK: - Properties
    var viewController: ___VARIABLE_sceneName___ViewController!
    var window: UIWindow!
    
    // MARK: - Methods
    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        viewController = ___VARIABLE_sceneName___ViewController()
    }
    
    override func tearDown() {
        super.tearDown()
        viewController = nil
    }
    // MARK: - Tests
    func test___VARIABLE_sceneName___InteractorExist() {
        // Given
        let interactorMock = ___VARIABLE_sceneName___ProtocolMock()
        
        // When
        viewController.rideInteractor = interactorMock
        
        // Then
        XCTAssertNotNil(viewController.___VARIABLE_sceneName___Interactor)
    }
    func testLoadView() {
        // Given
        // When
        viewController.loadView()
        // Then
        XCTAssertNotNil(viewController.view)
    }
}
