//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates, edited by
//  Behdad Keynejad for Snapp, so you can apply clean architecture to your
//  iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ___VARIABLE_sceneName___ViewController: SNPViewController {
    // MARK: - Properties
    var interactor: ___VARIABLE_sceneName___InteractorProtocol!
    var <#scene#>View: ___VARIABLE_sceneName___View = Bundle.load()
    static var lifetimeConfiguration: LifetimeConfiguration = (identifier: "___VARIABLE_sceneName___ViewController", maxCount: 1)
    
    // MARK: - Methods
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)

        trackLifetime()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)

        trackLifetime()
    }

    // MARK: UIViewController
    override func loadView() {
        view = <#scene#>View
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor.viewDidLoad?()
        
    }
}

extension ___VARIABLE_sceneName___ViewController: ___VARIABLE_sceneName___ViewControllerProtocol {
    func display(viewModel: ___VARIABLE_sceneName___.Something.ViewModel) {
        
    }
}
